### ISSUE TITLE
peer-peer code review-News-Week

### ISSUE THREAD

**Issue by fortuneonyeka** [IbrohimRasulov/Newsweek#1]
Please make sure the descendants of your unordered list are list items

**Comment by Edungit** [comment]
Kindly wrap the listed a tags in li tags

**Comment by YuvrajM108** [comment]
For the image src of the logo at the top you can use this link: https://upload.wikimedia.org/wikipedia/commons/d/db/Newsweek_Logo.svg

**Comment by kensayo** [comment]
**Looks good so far! Great job. 👏** 

- The footer section looks really good, I see you are using Bootstrap almost everywhere and that's how it should be. 
- Maybe you can add some margin in the bottom at navbar

Great job and keep going this way! 💪🏻

**Comment by DanSam5K** [comment]
Nice work you have going on so far with the footer section of the page!
Just a few missing closing tags and proper use of child element for ul tag 👏

**Comment by AbdumurodovaZulfizar** [comment]
Thank you for your help!

**Comment by DanteAlonsoHT** [comment]
**Nice!** The design looks very similar.
