### ISSUE TITLE
Morning Session - Stand-Up Meeting - 20/4

### ISSUE THREAD

**Issue by omar-labana** [IbrohimRasulov/Newsweek#8]

**Comment by enionsouza** [comment]
Your project looks very good, Ibrohim! Congrats on that!
Maybe, as a minor detail, you could only change the image in the Newsletter section, at the bottom of the page, so that it wouldn't stretch. That could be a `div` with a background image, like the original page.

**Comment by IbrohimRasulov** [comment]
Thanks very much, I will consider your suggestions
